versio: "3.8"

services:
 nestapp:
  build: ./
  ports: 
    - "3000:3000"
  env-file:
    - development.env
  depends_on:
    - postgresDB


  postgresDB:
    image: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - development.env

volumes:
  pgdata: